FROM docker.io/library/debian:stable-slim

LABEL com.github.containers.toolbox="true" \
      com.github.debarshiray.toolbox="true"

RUN apt-get update && \
    apt-get -y install build-essential sudo libcap2-bin && \
    apt-get clean

COPY alacritty.terminfo /
RUN tic -x alacritty.terminfo

RUN sed -i -e 's/ ALL$/ NOPASSWD:ALL/' /etc/sudoers

RUN touch /etc/localtime
RUN echo VARIANT_ID=container >> /etc/os-release

CMD /bin/bash
